version: '3.2'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lisa
      POSTGRES_PASSWORD: lisa
      POSTGRES_DB: lisa
            